# Generated by Django 5.1.4 on 2024-12-18 07:07

import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('rarity', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('QUEUED', 'queued'), ('GENERATING', 'generating'), ('CREATING_IMAGE', 'creating_image'), ('SAVING', 'saving'), ('COMPLETED', 'completed'), ('FAILED', 'failed'), ('NOT_FOUND', 'not_found')], default=myapp.models.TaskState['QUEUED'], max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
    ]
