# Generated by Django 5.1.4 on 2024-12-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manaCost', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(max_length=200)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('flavorText', models.TextField(blank=True, null=True)),
                ('rarity', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('powerToughness', models.CharField(blank=True, max_length=20, null=True)),
                ('local_image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
