# Generated by Django 5.1.4 on 2024-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='local_image_path',
        ),
        migrations.AddField(
            model_name='card',
            name='backblaze_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
